"""Verify static/graph.html was built correctly."""
c = open('static/graph.html', 'r', encoding='utf-8').read()
print('Size:', len(c), 'bytes')
print('Has inline data:', 'INLINE_GRAPH_DATA = {"nodes"' in c)
print('Has fetch fallback:', 'fetch' in c)
print('Has vis-network CDN:', 'vis-network.min.js' in c)
print('Has detail modal:', 'modal-box' in c)
print('Has tooltip:', 'vis-tooltip' in c)
print('Has legend:', 'bottombar' in c)
print('Has search:', 'search-input' in c)
print('Has filter pills:', 'filters' in c)
print('Has physics toggle:', 'btn-physics' in c)
print('Has upload/load data:', 'btn-upload' in c)
print('Has fullscreen:', 'btn-fullscreen' in c)
print('Has drag-and-drop upload:', 'upload-box' in c)
print('Has keyboard shortcut:', 'Ctrl+F' in c or 'metaKey' in c)
print('Server running on port 8000')
print('Open in browser: http://localhost:8000/static/graph.html')
